services:

  # Local services are available on their ports, but also available on:
  # http://api.localhost: backend
  proxy:
    image: traefik:3.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:80"
      - "8091:8080"
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --accesslog
      - --log
      - --log.level=DEBUG
      - --api
      - --api.insecure=true
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.middlewares.https-redirect.contenttype.autodetect=false
    networks:
      - traefik-public
      - default

  db:
    restart: "no"
    ports:
      - "5432:5432"

  auth-service:
    restart: "no"
    ports:
      - "8001:8000"
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./services/auth-service
          action: sync
          target: /app
          ignore:
            - ./services/auth-service/.venv
            - .venv
        - path: ./services/auth-service/pyproject.toml
          action: rebuild
    volumes:
      - ./services/auth-service/app:/app/app
      - ./services/auth-service/scripts:/app/scripts
    environment:
      EMAILS_FROM_EMAIL: "noreply@example.com"

networks:
  traefik-public:
    external: false
